### ISSUE TITLE
Getting Internal Error response

### ISSUE THREAD

**Issue by bernespinoza** [erikgrueter1/yelp-fusion#15]
Hello @erikgrueter1 

Since yesterday I'm experiencing Internal Error response, I couldn't find the source of the error but when I set back to this 81e621392b87e3c955eb5499c46cc64d7854567a it worked

#### Error
```ruby
Yelp::Fusion::Error::InternalError:
  Something went wrong internally, please try again later.
# /home/rof/cache/bundler/ruby/2.3.0/gems/yelp-fusion-0.3.pre.beta/lib/yelp/fusion/error.rb:32:in `validate'
# /home/rof/cache/bundler/ruby/2.3.0/gems/yelp-fusion-0.3.pre.beta/lib/yelp/fusion/error.rb:64:in `check_for_error'
# /home/rof/cache/bundler/ruby/2.3.0/gems/yelp-fusion-0.3.pre.beta/lib/yelp/fusion/endpoint/business.rb:64:in `business_request'
# /home/rof/cache/bundler/ruby/2.3.0/gems/yelp-fusion-0.3.pre.beta/lib/yelp/fusion/endpoint/business.rb:47:in `business'
# /home/rof/cache/bundler/ruby/2.3.0/gems/yelp-fusion-0.3.pre.beta/lib/yelp/fusion/singleton.rb:35:in `public_send'
# /home/rof/cache/bundler/ruby/2.3.0/gems/yelp-fusion-0.3.pre.beta/lib/yelp/fusion/singleton.rb:35:in `block in add_method'
```

**Comment by egrueter-dev** [comment]
@bernardoGalindoDiscoverySpecialists Were you able to find the origin?

**Comment by bernEsp** [comment]
No yet, I'm debugging it. Soon I'll have a better output.  @ocotopdf

**Comment by bernEsp** [comment]
I can't reproduce it. Probably the Yelp API was returning errors here https://github.com/erikgrueter1/yelp-fusion/blob/master/lib/yelp/fusion/endpoint/business.rb#L67, but then same day, next minute with old version worked. I'll continue testing and let you know. Thanks

**Comment by bernEsp** [comment]
We are getting this error querying `business` API but We are still debugging to determine if it is our data or something with yelp API

**Comment by egrueter-dev** [comment]
@bernardogalindo - any word on this?

**Comment by bernEsp** [comment]
@ocotopdf I think we can close it. The issue was related to bad data and valid api failures.

**Comment by egrueter-dev** [comment]
@bernardogalindo Thanks for the update. Let me know if anything else comes up!
