### ISSUE TITLE
 cannot load yelp-fusion

### ISSUE THREAD

**Issue by bernespinoza** [erikgrueter1/yelp-fusion#5]
There is an issue with the latest version of gem in rubygems and with this repo.  It is not loading all dependencies correctly. 

```ruby 
 require 'yelp-fusion'
LoadError: cannot load such file -- yelp-fusion
```

I tested adding the gem to the gemfile using the guidelines in the Readme and in ruby gems by the way they are different. I also installed the gem without bundler and the problem continues.

**Comment by erikgrueter1** [comment]
Hey @bernardoGalindoDiscoverySpecialists! Sorry this is not working for you.

Have you tried `gem install yelp-fusion --pre`? The gem is in pre-release.

**Comment by erikgrueter1** [comment]
See the rubygems site https://rubygems.org/gems/yelp-fusion

**Comment by bernespinoza** [comment]
Hello @erikgrueter1 

Actually I tested the option too. I was not able to perform `require 'yelp-fusion' ` What I realized is that this works `require 'yelp/fusion'`

There is also another possible issue comparing this implementation with the yelp-ruby. The old client instance contains the endpoint methods. What I actually did was to extend those methods and require the gem with the correct namespace and everything works as the old gem does. Here it is the branch without test but working on it (https://github.com/bernardogalindo/yelp-fusion/tree/feature/client-singleton-methods)

**Comment by erikgrueter1** [comment]
Interesting thank you bernardo! 

Take note that 
```ruby
gem 'yelp-fusion', '0.2.1-beta'
```
works for us in our rails app in production. Are you using rails? 

It looks like you are right, we are not defining Singleton methods on `Yelp::Fusion::Client` I look forward to your pull request!

**Comment by bernespinoza** [comment]
I'm not using rails is a ruby application. 

I'll test in rails app probably rails is inferring missing dependencies or knows how to translate 'yelp-fusion' to 'yelp/fusion'.

I'll report the result later today.

**Comment by bernespinoza** [comment]
@erikgrueter1 You are right. In rails app 'Rails 5.1.6'  and ruby version  '2.4.1' if try to create a yelp 
client it is possible and the gem works, however, if I try to require the `yelp-fusion` as the README file mentions it failed. I think this behavior is reasonable due the Bundler code to require Gems but, if we try to include the gem we should use this format `require 'yelp/fusion'` due the gem structure and file name.

```ruby
irb(main):002:0> client = Yelp::Fusion::Client.new('')
=> #<Yelp::Fusion::Client:0x007fd384698a70 @configuration=#<Yelp::Fusion::Configuration:0x007fd384698a20 @api_key="">>
```
require the  gem 

```ruby
require 'yelp-fusion'
LoadError: cannot load such file -- yelp-fusion
```

```ruby
irb(main):002:0> require 'yelp/fusion'
=> false #it returns false because rails | bundler has already included it
```

**Comment by erikgrueter1** [comment]
@bernardoGalindoDiscoverySpecialists That makes sense. I also like the addition of the singleton methods you mentioned. Can you please open a PR to add them and I will review it?

Thank you for your work!
-Erik

**Comment by bernespinoza** [comment]
@erikgrueter1 here it is => https://github.com/erikgrueter1/yelp-fusion/pull/6

**Comment by lkatzman** [comment]
Hi @bernardoGalindoDiscoverySpecialists 
I released the new version on Ruby Gems. Could you let me know once you've tested it out and can confirm it is working? Thank you!!

**Comment by bernespinoza** [comment]
@lkatzman thanks for that. I'll install today and let you know the result.

**Comment by bernEsp** [comment]
@lkatzman @erikgrueter1 I tested this gem in production and overall it is working very well besides minor changes in api responses an extra calls to get more data from business everything is working and the transaction (yelp to yelp-fusion) was very smooth therefore I think, We can close this issue.

**Comment by erikgrueter1** [comment]
Great @bernardogalindo Please let us know if you have any other issues with the Gem!
